[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv", "nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend && python -m venv venv",
  "cd backend && source venv/bin/activate && pip install -r requirements.txt",
  "cd frontend && npm install && npm run build"
]

[start]
cmd = "cd backend && source venv/bin/activate && python app.py"
